server:
  http: "\${SERVER_PORT:8080}"

spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  threads:
    virtual:
      enabled: "\${VIRTUAL_THREADS_ENABLED:true}"
  cache:
    type: redis
  data:
    redis:
      host: "\${REDIS_HOST:}"
      port: "\${REDIS_PORT:}"
      password: "\${REDIS_PASSWORD:}"
      ssl.enabled: "\${REDIS_SSL_ENABLED:false}"
  security:
    oauth2:
      client:
        registration:
          oneidentity:
            provider: oneidentity
            client-id: \${AUTH_CLIENT_ID:}
            client-secret: \${AUTH_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            redirect-uri: \${AUTH_CLIENT_REDIRECT_URI:}
            scope: openid
        provider:
          oneidentity:
            issuer-uri: \${AUTH_ISSUER_URI:}
            authorization-uri: \${AUTH_CLIENT_AUTHORIZATION_URI:}
            token-uri: \${AUTH_CLIENT_TOKEN_URI:}
            user-name-attribute: sub
            jwk-set-uri: \${AUTH_CLIENT_JWK_URI:}
white-list-cf-users: \${WHITE_LIST_USERS:}

jwt:
  audience: "\${JWT_TOKEN_AUDIENCE:application-audience}"
  tokenType: "\${JWT_TOKEN_TYPE:Bearer}"
  access-token:
    expire-in: "\${JWT_TOKEN_EXPIRATION_SECONDS:3600}"
    private-key: "\${JWT_TOKEN_PRIVATE_KEY:}"
    public-key: "\${JWT_TOKEN_PUBLIC_KEY:}"

zendesk-assistance:
  tokenType: JWT
  return-to: \${HELP_CENTER_URL:}
  action-url: \${ZENDESK_ACTION_URL:}
  assistance-token:
    product-id: \${ASSISTANCE_ZENDESK_PRODUCT_ID:}
    organization: \${ASSISTANCE_ZENDESK_ORGANIZATION:}
    private-key: \${JWT_TOKEN_ASSISTANCE_ZENDESK_PRIVATE_KEY:}

rest-client:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"
  biz-events:
    paid-notice:
      baseUrl: \${BIZ_EVENTS_PAID_NOTICE_BASE_URL:}
      api-key: \${BIZ_EVENTS_PAID_NOTICE_SERVICE_API_KEY:}
  pull-payment:
    baseUrl: \${PULL_PAYMENT_BASE_URL:}
    api-key: \${PULL_PAYMENT_SERVICE_API_KEY:}
  gpd:
    baseUrl: \${GPD_SERVICE_BASE_URL:}
    api-key: \${GPD_SERVICE_API_KEY:}
  auth:
    base-url: "\${AUTH_SERVER_BASE_URL:}/payhub"
    max-attempts: "\${AUTH_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${AUTH_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${AUTH_PRINT_BODY_WHEN_ERROR:true}"
    post-token:
      client_secret: "\${P4PA_AUTH_CLIENT_SECRET:clientsecret}"
  citizen:
    base-url: "\${CITIZEN_SERVER_BASE_URL:}"
    max-attempts: "\${CITIZEN_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${CITIZEN_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${CITIZEN_PRINT_BODY_WHEN_ERROR:true}"

springdoc:
  writer-with-default-pretty-printer: true

spontaneous-mock-paths:
  organizationList: "mock/organizationsMock.json"

logging:
  level:
    it.gov.pagopa.arc.connector: \${LOGGING_LEVEL_ARC_CONNECTOR:DEBUG}
    org:
      springframework:
        security: INFO
        web: INFO
        session:
          web:
            http:
              SessionRepositoryFilter: INFO

management:
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,redis
  endpoints:
    web:
      exposure.include: health